export const languages = [
  { label: "Auto-Detect", value: "default", wer: 0 },
  { label: "Indonesian", value: "id", wer: 7.2 },
  { label: "English", value: "en", wer: 9.3 },
  { label: "Arabic", value: "ar", wer: 15.1 },
  { label: "Japanese", value: "ja", wer: 10.3 },
  { label: "Korean", value: "ko", wer: 5.2 },
  { label: "Dutch", value: "nl", wer: 4.3 },
  { label: "Spanish", value: "es", wer: 4.7 },
  { label: "Italian", value: "it", wer: 5.5 },
  { label: "German", value: "de", wer: 5.7 },
  { label: "Thai", value: "th", wer: 5.8 },
  { label: "Russian", value: "ru", wer: 5.8 },
  { label: "Portuguese", value: "pt", wer: 5.9 },
  { label: "Polish", value: "pl", wer: 6.0 },
  { label: "Mandarin (TW)", value: "zh-TW", wer: 8.2 },
  { label: "Swedish", value: "sv", wer: 8.3 },
  { label: "Czech", value: "cs", wer: 9.0 },
  { label: "French", value: "fr", wer: 10.8 },
  { label: "Romanian", value: "ro", wer: 10.8 },
  { label: "Cantonese (CN)", value: "yue-CN", wer: 10.9 },
  { label: "Turkish", value: "tr", wer: 12.0 },
  { label: "Mandarin (CN)", value: "zh-CN", wer: 12.6 },
  { label: "Catalan", value: "ca", wer: 13.3 },
  { label: "Hungarian", value: "hu", wer: 13.4 },
  { label: "Ukrainian", value: "uk", wer: 13.6 },
  { label: "Greek", value: "el", wer: 13.7 },
  { label: "Bulgarian", value: "bg", wer: 14.3 },
  { label: "Serbian", value: "sr", wer: 15.7 },
  { label: "Macedonian", value: "mk", wer: 15.8 },
  { label: "Cantonese (HK)", value: "yue-HK", wer: 15.9 },
  { label: "Latvian", value: "lv", wer: 16.7 },
  { label: "Slovenian", value: "sl", wer: 16.8 },
  { label: "Hindi", value: "hi", wer: 16.9 },
  { label: "Galician", value: "gl", wer: 18.0 },
  { label: "Danish", value: "da", wer: 18.1 },
  { label: "Urdu", value: "ur", wer: 20.4 },
  { label: "Slovak", value: "sk", wer: 23.4 },
  { label: "Hebrew", value: "he", wer: 23.5 },
  { label: "Finnish", value: "fi", wer: 24.6 },
  { label: "Azerbaijani", value: "az", wer: 24.8 },
  { label: "Lithuanian", value: "lt", wer: 27.6 },
  { label: "Estonian", value: "et", wer: 29.9 },
  { label: "Nynorsk", value: "nn", wer: 30.7 },
  { label: "Welsh", value: "cy", wer: 32.0 },
  { label: "Punjabi", value: "pa", wer: 34.7 },
  { label: "Afrikaans", value: "af", wer: 36.0 },
  { label: "Persian", value: "fa", wer: 37.4 },
  { label: "Basque", value: "eu", wer: 38.9 },
  { label: "Vietnamese", value: "vi", wer: 39.8 },
  { label: "Bengali", value: "bn", wer: 40.3 },
  { label: "Nepali", value: "ne", wer: 40.4 },
  { label: "Marathi", value: "mr", wer: 41.2 },
  { label: "Belarusian", value: "be", wer: 43.7 },
  { label: "Kazakh", value: "kk", wer: 47.6 },
  { label: "Armenian", value: "hy", wer: 48.1 },
  { label: "Swahili", value: "sw", wer: 51.2 },
  { label: "Tamil", value: "ta", wer: 51.5 },
  { label: "Albanian", value: "sq", wer: 55.7 },
];
